fail_fast: false
repos:
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "1.1.0"
  hooks:
    - id: sync_with_poetry
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v2.3.0'
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: pretty-format-json
      args:
        - "--autofix"
    - id: mixed-line-ending
    - id: requirements-txt-fixer
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 'v1.10.0'
  hooks:
    - id: python-no-eval
    - id: python-check-blanket-type-ignore
    - id: python-check-blanket-noqa
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.4.10'
  hooks:
    - id: ruff
      args: [--fix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.10.1'
  hooks:
    - id: mypy
      args: ["--ignore-missing-imports"]
