name: run-tests-and-pre-commits

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  test-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
      - name: Cache Poetry environment
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Set Poetry configuration
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run pre-commits
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all
      - name: Run unit tests
        run: poetry run pytest -vv
